apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tbhome-storage-repo
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: Storage/
    repoURL: 'https://github.com/ThorTheStorm/TBHome.git'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
