kind: PersistentVolume
apiVersion: v1
metadata:
  name: gitea-pv-storage
  labels:
      type: local
  namespace: gitea
spec:
  capacity:
    storage: 10Gi
  accessModes:
  -  ReadWriteOnce
  hostPath:
    path: "/mnt/kubernetes/gitea-pv"