apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: tbhome-letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: tor.egil@tbhome.no
    privateKeySecretRef:
      name: tbhome-letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: public